version: '2'
services:
  web:
    build: .
    restart: always
    # env_file: ./server/.env # TODO - uncomment this to auto-load your .env file!
    environment:
      NODE_ENV: production
      PORT: 8000
    labels:
      - "traefik.frontend.rule=Host:web.test.local"
      - "traefik.port=8000"
      - "traefik.enable=true"
  traefik:
    image: traefik:alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
    ports:
      - 80:80
